version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak_password
    ports:
      - "2000:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - keycloak-network
    depends_on:
      - db
    command:
      - start-dev

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - keycloak-network

volumes:
  keycloak-data:
  postgres-data:

networks:
  keycloak-network:
