version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak_password
      - KC_HTTP_ENABLED=true
      - KC_HTTPS_ENABLED=false
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_LOG_LEVEL=DEBUG
      - KC_SPI_THEME_STATIC_MAX_AGE=-1
      - KC_HOSTNAME=http://37.194.168.90
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_ADMIN_URL=http://http://37.194.168.90:2020
      - KC_HOSTNAME_URL=http://http://37.194.168.90:2020

    ports:
      - "2020:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - keycloak-network
    depends_on:
      db:
        condition: service_healthy
    command: [ "start-dev" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/master"]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: postgres:17
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  keycloak-data:
  postgres-data:

networks:
  keycloak-network:
